= RISC-V Platform Security Model Specification

This repository holds specifications which define a platform security model for RISC-V platforms.

= License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0).
See the https://github.com/riscv/docs-spec-template/blob/main/LICENSE[LICENSE] file for details.

= Contributors

Contributors to this specification are listed link:specification/src/contributors.adoc[here].

= Dependencies

This project is built using AsciiDoctor (Ruby). The project's repository has been setup to automatically build a PDF
version on a commit using GitHub actions.  Workflow dependencies are located in the `dependencies` directory.

For more information on AsciiDoctor, specification guidelines, or building locally, see the
https://github.com/riscv/docs-dev-guide[RISC-V Documentation Developer Guide].

= Cloning the project

This project uses https://git-scm.com/book/en/v2/Git-Tools-Submodules[GitHub Submodules]
to include the https://github.com/riscv/docs-resources[RISC-V docs-resources project]
to achieve a common look and feel.

The project repository uses git submodules which must be cloned explicitly. This can be done when cloning the repository
the first time by executing either:

`git clone --recurse-submodules`

or:

`git submodule init` followed by `git submodule update`

Failure to do so will result in an error while building the pdf:

```
$ make
  asciidoctor-pdf \
  -a toc \
  -a compress \
  -a pdf-style=docs-resources/themes/riscv-pdf.yml \
  -a pdf-fontsdir=docs-resources/fonts \
  --failure-level=ERROR \
  -o profiles.pdf profiles.adoc

  asciidoctor: ERROR: could not locate or load the built-in pdf theme
  docs-resources/themes/riscv-pdf.yml; reverting to default theme

  No such file or directory - notoserif-regular-subset.ttf not found in docs-resources/fonts
    Use --trace for backtrace
  make: *** [Makefile:7: profiles.pdf] Error 1
```

= Building the document

The final specification can be generated in PDF form using the `make` command at the project root.