
[[chapter1]]

== Introduction

This specification provides guidelines for how RISC-V security building blocks
can be used to build secure systems for different use cases. It is
aimed at developers of RISC-V technical specifications, as well as at designers
of secure RISC-V systems.

A few example uses cases based on commonly used deployment models are provided.
These use cases are not intended to be exhaustive, or to act as formal _protection
profiles_ (https://csrc.nist.gov/glossary/term/protection_profile). They are intended as templates to be used as general guidelines,
which can be applied to a wide variety of use cases.

The examples may be extended over time as required. Protection profiles for more
specific use cases are expected to be provided within relevant certification
bodies, or as separate RISC-V specifications if required.

=== Requirements and tracking

Where this specification makes formal recommendations, those are captured as
trackable requirements using the following format:

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_CAT_NNN
| The `SR_CAT` is a "Security Requirement CATegory" prefix that logically groups
the requirements (e.g. SR_UPD denotes security requirements related to updates,
and SR_ATT denotes security requirements related to attestation) and is followed
by 3 digits - `NNN` - assigning a numeric ID to the requirement.

The requirements use the key words "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY",
and "OPTIONAL" that are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119] when, and only when, they appear
in all capitals, as shown here. When these words are not capitalized, they have
their normal English meanings.
|===

A requirement or a group of requirements may be followed by non-normative text
providing context or justification for the requirement. The non-normative text
may also be used to reference sources that are the origin of the requirement.

Trackable requirements are intended for ease of reference across dependent
specifications.

=== Relationship to external profiles

For the purpose of this specification, external standard or protection profiles apply to existing
ecosystems or segments, but do not generally mandate implementations or
architectures. This specification does not aim to establish new protection profiles. Its
main purpose is to provide guidelines for how RISC-V security building blocks
can be used to build RISC-V products which can comply with existing profiles.

Some protection profiles cover some or all of:

* Security reference architectures and taxonomy
* Hardware and software security requirements
* Interfaces and programming models
* Protection profiles and certification programs
* Reference firmware/software

Other protection profiles are focused on processes and methodology.

Examples of external protection profiles include:

[width=100%]
[%header, cols="5,15"]
|===
| Profile
| Description

| Global Platforms (GP)
| Trusted execution environments(TEE) and trusted firmware for mobile,
connected clients, and IoT. +
Secure element (SE) for tamper resistant storage of and operations on
cryptographic secrets. +
SESIP certification. +
https://globalplatform.org/

| Platform Security Architecture (PSA)
| Platform security requirements for connected devices. +
PSA Certified. +
https://www.psacertified.org/


| Trusted computing group (TCG)
| Trusted platform module (TPM) and Device identifier composition engine (DICE)
for trusted platforms. +
TCG certification. +
https://trustedcomputinggroup.org/


| Confidential computing consortium
| Common principles and protocols for protecting data in use (confidential
computing). +
https://confidentialcomputing.io/

| NIST
| Widely used US standards for security processes, protocols and algorithms.
Examples for the purposes of this specification: +
NISTIR 8259 - IoT device cybersecurity capability +
SP800-207 - Zero Trust Architecture +
https://www.nist.gov/
|===

This is not an exhaustive list, more examples can be found in the reference
section of this specification.
