[[chapter3]]

== RISC-V security building blocks

This chapter outlines brief descriptions of RISC-V security building blocks
discussed in this specification, together with general guidelines and links to
technical specifications.

See also the reference use cases chapter of this specification for common
examples of how RISC-V security building blocks can be combined.

=== Isolation

Isolation enable separation of software components executing on a Hart, as well
as device assignment. RISC-V enables:

* Privilege based isolation
* Physical memory access control (hart and device-initiated accesses)
* Virtual memory management (hart and device virtualization)
* Hypervisor extension
* Supervisor domains

==== Privilege levels

https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA]

Standard privilege levels - Machine mode (M), Supervisor mode (S), and User
mode (U) - enable separation of more privileged software from less privileged
software.

==== Hypervisor extension

https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA]

Hypervisor extension supports standard supervisor level hypervisors. It extends
S mode into Hypervisor-extended supervisor mode (HS), and a virtual supervisor
mode (VS) for guests. It also extends U mode into standard user mode (U) and
virtual user mode (VU).

Isolation of guests is enforced using two-stage address translation and
protection.  Two-stage address translation and protection is in effect in VS
and VU modes.

Alternatively sPMP can be used instead of MMU to support static partition
hypervisors, for example on systems with hard and deterministic real time
requirements [Note -The sPMP for Hypervisor extension has not been specified
yet].

MMU, PMP/ePMP, and sPMP are discussed later in this chapter.

==== PMA
https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA]

_Physical memory attributes (PMA)_ are intended to capture inherent properties
of the underlying hardware. For example, read-only ROM regions, or non-cachable
device regions. Often PMA can be fixed at design time or at boot, but sometimes
runtime PMA can be required.

A separate hardware checker - _PMA checker_ - enforces PMA rules at runtime once
a physical address is known. PMA rules are always checked on every physical
access, and typically configured by region.

==== PMP and ePMP

https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA]

_Physical memory protection (PMP)_ enables M-mode to access-control physical
memory for supervisor and U modes (with or without H-extension).

[#cat_sr_sub_pmp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_001
| PMP configurations MUST only be directly accessible to machine mode
|===

Individual access controlled regions can be locked until the next system reset
to create temporal isolation boundaries, such as protecting immutable boot code.

ePMP extends PMP protection by allowing machine mode to restrict its own access
to memory allocated to lower privilege levels. This can be used to mitigate
against privilege escalation attacks, for example.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_002
| If PMP is supported then ePMP MUST be supported.
|===

==== sPMP

https://github.com/riscv/riscv-spmp

_Supervisor PMP (sPMP)_ enables supervisor mode to control physical memory
access for U mode.

sPMP allows supervisor mode to restrict its own access to memory allocated to
lower privilege levels. This can be used to mitigate against privilege
escalation attacks, for example.

When combined with H-extension, sPMP can be nested so that the hypervisor can
control memory allocations to its guests, and each guest can control its own
memory allocations to its workloads.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_003
| If MMU is not supported, sPMP SHOULD be used to protect S-mode from lower privilege levels.
|===

==== MMU

https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA]

_Memory management unit (MMU)_ enables address translation and protection for:

* Isolating an OS from workloads on a system without H-extension (one-stage
translation)
* Isolating a hypervisor from a guest, on a system with H-extension (two-stage
translation)

[#cat_sr_sub_mmu]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MMU_001
| Either PMP/ePMP or MTT MUST be used to protect M-mode from lower privilege
levels.

| SR_MMU_002
| if Sv is supported 1st-stage and/or G-stage page tables MUST used to protect
Supervisor domain H/S-mode from lower privilege levels.
|===

==== Supervisor domains

https://github.com/riscv/riscv-smmtt

Supervisor domains allow software components on the same hart to be developed,
certified, deployed and attested independently of each other.

A supervisor domain is a compartment above M-mode, physically isolated -
memory, execution state, and devices - from other supervisor domains regardless
of privilege level (below M-mode). Isolation and context switching between
supervisor domains are managed by M-mode firmware.

A supervisor domain is identified at architecture level by a _supervisor domain
id (SDID)_, managed by M-mode firmware.

[cat_sr_sub_sud]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_SUD_001
| PMP/ePMP or MTT MUST be used to enforce physical memory isolation
boundaries for supervisor domains, and to protect machine mode from any
supervisor domain.

|===

PMP can be used for more static and deterministic use cases.

MTT can be used where more fine grained dynamic resource management across
supervisor domain boundaries is required.

NOTE: MTT can be sufficient for protecting Root domain in the sense that M-mode
can enforce that its own resources are never assigned to another domain.
PMP/ePMP still add further protections for M-mode, such as the ability to
implement temporal isolation boundaries within M-mode (for example, protect
early boot code), or to prevent itself from accessing or executing from memory
assigned to lower privilege levels (privilege escalation).

[width=100%]
[%header, cols="5,20"]
|===

| ID#
| Requirement

| SR_SUD_002
| A system supporting supervisor domains MUST support supervisor domain
extensions for interrupts (Smsdia) and SHOULD support supervisor domain
extensions for external debug (TBD).

|===

Interrupts: https://github.com/riscv/riscv-smmtt +
External debug: https://github.com/riscv-non-isa/riscv-external-debug-security +
Performance counters: https://lists.riscv.org/g/tech-privileged

These extensions enable management of interrupts, external debug, and
performance counters across supervisor domain boundaries. M-mode firmware
should context switch hart HPM event/counters to manage isolation of
performance counters:

* External debug can be enabled for one supervisor domain without affecting
other supervisor domains
* M-mode firmware manage interrupt routing and preemption across supervisor
domain boundaries
* M-mode firmware can ensure that performance counters cannot be used by
software in one supervisor domain to measure operations in other supervisor
domains

==== MTT

https://github.com/riscv/riscv-smmtt

The _memory tracking table (MTT)_ is a memory structure managed by machine
mode, tracking memory ownership across supervisor domains. It is designed to
enable fine grained dynamic memory management across supervisor domain
boundaries, with policy typically set by a hypervisor in a hosting domain
responsible for resource management.

[#cat_sr_sub_mtt]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MTT_001
| Either PMP/ePMP or MTT MUST be used to protect M-mode from lower privilege
levels

| SR_MTT_002
| MTT configurations MUST only be directly accessible to machine mode
|===

NOTE: MTT can be sufficient for protecting Root domain in the sense that M-mode
can enforce that its own resources are never assigned to another domain.
PMP/ePMP still add further protections for M-mode, such as the ability to
implement temporal isolation boundaries within M-mode (for example, protect
early boot code), or to prevent itself from accessing or executing from memory
assigned to lower privilege levels (privilege escalation).

==== IOPMP

https://github.com/riscv-non-isa/iopmp-spec

IOPMP is a system level component providing physical memory access control for
device-initiated transactions, complementing PMP and sPMP rules.

[#cat_sr_sub_iop]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOP_001
| A system which supports PMP/ePMP, or sPMP, MUST implement IOPMP for device
access control unless the system supports IOMTT.

Depending in system design, IOMTT can enforce the same access control policies as IOPMP.

| SR_IOP_002
| IOPMP configurations MUST only be directly accessible to machine mode.
|===

NOTE: IOPMP defines multiple "models" for different system configurations.
Unless specified differently in the use cases in this specification, system
designers are free to choose any IOPMP model.

==== IOMTT

https://github.com/riscv/riscv-smmtt

IOMTT is a system level component providing physical memory access control for
device-initiated transactions, complementing MTT rules.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_001
| A system which supports MTT MUST implement IOMTT for access-control for
device-initiated memory accesses.

| SR_IOM_002
| IOMTT configurations MUST only be directly accessible to machine mode.

| SR_IOM_003
| A system which implements IOMTT MAY also implement IOPMP to access-control
device-initiated access to M-mode memory.

|===

NOTE: IOMTT can also be sufficient for protecting Root devices in the sense that
M-mode can enforce that its own resources are never assigned to another domain.
Use of IOPMP or similar still adds further protections. For example, a system
may require that Root devices are not able to access memory assigned to TEE
domain.

==== IOMMU

https://github.com/riscv-non-isa/riscv-iommu

IOMMU is a system level component performing memory address translation from IO
Virtual Address to Physical Address, allowing devices to access virtual memory
locations. It complements MMU configurations.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_004
| Systems supporting MMU SHOULD also support IOMMU

| SR_IOM_005
| Systems supporting IOMMU MUST also enforce physical memory access control for
M-mode memory against device-initiated transactions (IOMTT or IOPMP).

|===

=== Software enforced memory tagging

https://github.com/riscv/riscv-j-extension

_Memory tagging (MT)_, is a technique which can improve the memory safety of an
application. A part of the effective address of a pointer can be masked off,
and used as a tag indicating intended ownership or state of a pointer. The tag
can be used to track accesses across different regions, as well as protecting
against pointer misuse such as "use after free". The pointer masking should use
the proposed J-extension pointer masking extension (Smpm, Smnpm, Ssnpm).

With software based memory tagging the access rules encoded in tags are
enforced by software (compiler).

See also hardware enforced memory tagging below.

=== Control flow integrity

https://github.com/riscv/riscv-cfi

Control-flow Integrity (CFI) capabilities help defend against Return-Oriented
Programming (ROP) and Call/Jump-Oriented Programming (COP/JOP) style
control-flow subversion attacks, where an attacker attempts to modify return
addresses or call/jump address to redirect a victim to code reused by the
attacker.

These attack methodologies use code sequences in authorized modules, with at
least one instruction in the sequence being a control transfer instruction that
depends on attacker-controlled data either in the return stack or in memory
used to obtain the target address for a call or jump. Attackers stitch these
sequences together by diverting the control flow instructions (e.g., JALR,
C.JR, C.JALR), from their original target address to a new target via
modification in the return stack or in the memory used to obtain the jump/call
target address.

RISC-V provides two defenses:

* Shadow stacks (Zicfiss) - protect return addresses on call stacks
* Labeled Landing pads (Zicfilp) - protect target addresses in jumps and
branches

=== Cryptography

https://github.com/riscv/riscv-crypto

RISC-V includes ISA extensions in the following cryptographic areas:

* Scalar cryptography
* Vector cryptography
* Entropy source (scalar)

RISC-V cryptographic extensions are aimed at supporting efficient acceleration
of cryptographic operations at ISA level. This can both help reduce the TCB of
an isolated component, and avoid hardware bottlenecks (for example, system
level cryptographic subsystems).

The entropy source extension provides an ISA level interface to a hardware
entropy source. Entropy source requirements can depend on use case or ecosystem
specific requirements and RISC-V does not provide any entropy source technical
specification. But the entropy source ISA specification does contain general
recommendations and references.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_CPT_001
| RISC-V systems SHOULD support either scalar or vector cryptographic ISA
extensions

| SR_CPT_002
| The entropy source ISA extension MUST be supported if either scalar or vector
cryptographic ISA extensions are supported.

|===

It is not necessary to support both scalar and vector operations, as a scalar
operation can be viewed as a vector of size 1.

=== Roadmap

==== Capability based architecture

* Cheri
* Capstone

==== Hardware enforced memory tagging

Hardware enforced memory tagging extends software based memory tagging (see
above) by moving enforcement of tagged rules to hardware.

==== HFI

_Hardware-assisted fault isolation (HFI)_ aims to provide lightweight
in-process isolation to mitigate against errors in one process compromising
other processes within the same workload.

==== Lightweight isolation

* TBD

==== System integration

* WorldGuard

==== Cryptography enhancements

* PQ
* High assurance computing (HAC)
