
[[chapter1]]

== Introduction

This specification provides guidelines for building secure RISC-V systems using RISC-V security building blocks. It is
aimed at developers of RISC-V technical specifications as well as designers of secure RISC-V systems.

A few example use cases are provided which are based on commonly used security deployment models.
These are not intended to be exhaustive. They are accompanied by use case specific security
guidelines which may help readers implement their own guidelines for their specific use cases.

The examples may be extended over time as required.

The examples are not definitions of formal Protection Profiles (See: https://csrc.nist.gov/glossary/term/protection_profile).
Such protection profiles for specific use cases are expected to be provided within relevant certification
bodies or as separate RISC-V specifications, if required.

=== Requirements and tracking

This is a non-normative specification. However, the specification makes formal recommendations where appropriate. Those
are expressed as trackable requirements using the following format:

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_CAT_NNN
| The `SR_CAT` is a "Security Requirement CATegory" prefix that logically groups
the requirements (e.g. SR_UPD denotes security requirements related to updates,
and SR_ATT denotes security requirements related to attestation) and is followed
by 3 digits - `NNN` - assigning a numeric ID to the requirement.

The requirements use the key words "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY",
and "OPTIONAL" that are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119] when, and only when, they appear
in all capitals, as shown here. When these words are not capitalized, they have
their normal English meanings.
|===

A requirement or a group of requirements may be followed by non-normative text
providing context or justification for the requirement. The non-normative text
may also be used to reference sources that are the origin of the requirement.

Trackable requirements are intended for ease of reference across dependent
specifications.

=== Relationship with external protection profiles

To assist with articulating security guidelines relevant to the included examples, this specification references external
protection profiles as appropriate. Such references are not intended to mandate any specific implementations, but to provide guidelines on how RISC-V security building blocks may be used to comply with those protection profiles.

Typically, protection profiles cover some or all of:

* Security reference architectures and taxonomy
* Hardware and software security requirements
* Interfaces and programming models
* Reference firmware/software
* Certification programs
* Misc Processes and methodology

The following are examples of some external protection profiles that are referenced by this specification:

[width=100%]
[%header, cols="5,15"]
|===
| Profile
| Description

| Global Platforms (GP)
| Trusted execution environments(TEE) and trusted firmware for mobile,
connected clients, and IoT. +
Secure element (SE) for tamper resistant storage of and operations on
cryptographic secrets. +
SESIP certification. +
https://globalplatform.org/

| Platform Security Architecture (PSA)
| Platform security requirements for connected devices. +
PSA Certified. +
https://www.psacertified.org/

| Trusted computing group (TCG)
| Trusted platform module (TPM) and Device identifier composition engine (DICE)
for trusted platforms. +
TCG certification. +
https://trustedcomputinggroup.org/

| Confidential computing consortium
| Common principles and protocols for protecting data in use (confidential
computing). +
https://confidentialcomputing.io/

| NIST
| Widely used US standards for security processes, protocols and algorithms.
Examples for the purposes of this specification: +
NISTIR 8259 - IoT device cybersecurity capability +
SP800-207 - Zero Trust Architecture +
https://www.nist.gov/
|===

This is not an exhaustive list, more examples can be found in the reference
section of this specification.