[[chapter3]]

== RISC-V security building blocks

This chapter outlines brief descriptions of RISC-V security building blocks
discussed in this specification, together with general guidelines and links to
technical specifications.

See also the reference use cases chapter of this specification for common
examples of how RISC-V security building blocks can be combined.

=== Isolation

Isolation enables access restrictions on software components executing on a hart, as well
as on device accesses. RISC-V enables:

* Privilege based isolation
* Physical memory access control (hart and device-initiated accesses)
* Virtual memory management (hart and device virtualization)
* Hypervisor extension
* Supervisor domains

==== Privilege levels

*See section 1.2 (Privilege Levels) of the https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA] specification.*

Standard privilege levels - Machine mode (M), Supervisor mode (S), and User
mode (U) - enable separation of more privileged software from less privileged
software.

==== Hypervisor extension

*See chapter 8 (Hypervisor Extension) of the https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA] specification.*

The Hypervisor extension supports standard supervisor level hypervisors. It extends
S mode into Hypervisor-extended supervisor mode (HS), and a virtual supervisor
mode (VS) for guests. It also extends U mode into standard user mode (U) and
virtual user mode (VU).

Isolation of guests is enforced using two-stage address translation and
protection.  Two-stage address translation and protection is in effect in VS
and VU modes.

Alternatively sPMP can be used instead of MMU to support static partitionining
hypervisors, for example on systems with hard and deterministic real time
requirements [Note -The sPMP for Hypervisor extension has not been specified
yet].

MMU, PMP/Smepmp, and sPMP are discussed later in this chapter.

==== PMA

*See section 3.6 (Physical Memory Attributes) of the https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA] specification.*

_Physical memory attributes (PMA)_ are intended to capture inherent properties
of the underlying hardware. For example, read-only ROM regions, or non-cachable
device regions. Often PMA can be fixed at design time or at boot, but sometimes
runtime PMA can be required.

A separate hardware checker - _PMA checker_ - enforces PMA rules at runtime once
a physical address is known. PMA rules are always checked on every physical
access, and typically configured by region.

==== PMP

*See section 3.7 (Physical Memory Protection) of the https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA] specification.*

_Physical memory protection (PMP)_ enables M-mode to access-control physical
memory for supervisor and U modes (with or without H-extension).

[#cat_sr_sub_pmp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_001
| PMP configurations MUST only be directly accessible to machine mode
|===

Individual access controlled regions can be locked until the next system reset
to create temporal isolation boundaries, such as protecting immutable boot code.

==== Smepmp

*See the https://github.com/riscv/riscv-tee/blob/main/Smepmp/Smepmp.pdf[PMP Enhancements for memory access and execution prevention on Machine mode] specification.*

Smepmp extends PMP protection by allowing machine mode to restrict its own access to memory allocated to lower privilege levels. This can be
used to mitigate against privilege escalation attacks.

[#cat_sr_sub_smepmp]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_002
| If PMP is supported then Smepmp MUST be supported.
|===

==== sPMP

*See the https://github.com/riscv/riscv-spmp[RISC-V S-mode Physical Memory Protection (SPMP)] specification.*

_Supervisor PMP (sPMP)_ enables supervisor mode to control physical memory
access for U mode.

sPMP allows supervisor mode to restrict its own access to memory allocated to
lower privilege levels. This can be used to mitigate against privilege
escalation attacks, for example.

When combined with H-extension, sPMP can be nested so that the hypervisor can
control memory allocations to its guests, and each guest can control its own
memory allocations to its workloads.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_PMP_003
| If MMU is not supported, sPMP SHOULD be used to protect S-mode from lower privilege levels.
|===

==== MMU

*See sections 4.3 to 4.6 (Page-Based Virtual-Memory Systems) of the https://github.com/riscv/riscv-isa-manual/releases/tag/Priv-v1.12[Privileged
ISA] specification.*

_Memory management unit (MMU)_ enables address translation and protection for:

* Isolating an OS from workloads on a system without H-extension (one-stage
translation)
* Isolating a hypervisor from a guest, on a system with H-extension (two-stage
translation)

[#cat_sr_sub_mmu]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MMU_001
| Either PMP/Smepmp or MTT MUST be used to protect M-mode from lower privilege
levels.

| SR_MMU_002
| if the Sv extension is supported then 1st-stage page tables MUST used to protect
the S-Mode Supervisor domain from accesses made by U-Mode.

| SR_MMU_003
| if the H extension is supported 1st-stage and/or G-stage page tables MUST used to protect
Supervisor domain H/S-mode from lower privilege levels.
|===

==== MTT

*See the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor Domains Access
Protection] specification.*

The _memory tracking table (MTT)_ is a memory structure managed by machine
mode that is used to track memory ownership across supervisor domains. It is designed to
enable fine grained dynamic memory management across supervisor domain
boundaries, with policy typically set by a hypervisor in a hosting domain
responsible for resource management.

[#cat_sr_sub_mtt]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_MTT_001
| Either PMP/Smepmp or MTT MUST be used to protect M-mode from lower privilege
levels

| SR_MTT_002
| MTT configurations MUST only be directly accessible to machine mode
|===

NOTE: The M-Mode resident software responsible for managing context switches and communication between supervisor
domains is called the Root Domain. An MTT can be sufficient for protecting the Root Domain by enabling M-mode
to ensure that its own resources are never assigned to any another domain.
The use of PMP/Smepmp will add yet further protections for M-mode, such as the ability to
implement temporal isolation boundaries within M-mode (to protect
early boot code, for example), or to prevent itself from accessing or executing from memory
assigned to lower privilege levels (privilege escalation).

==== Supervisor domains

*See the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor Domains Access
Protection] specification.*

Supervisor domains allow software components on the same hart to be developed,
certified, deployed and attested independently of each other.

A supervisor domain is an S-Mode compartment that is physically isolated from other supervisor domains. The memory,
execution state and devices belonging to a supervisor domains are isolated from other supervisor domains.
This isolation of supervisor domains and the context switching between them is managed by M-mode firmware.

A supervisor domain is identified at an architecture level by a _supervisor domain
id (SDID)_ CSR, managed by M-mode firmware.

[cat_sr_sub_sud]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_SUD_001
| PMP/Smepmp or MTT MUST be used to enforce physical memory isolation
boundaries for supervisor domains, and to protect machine mode from any
supervisor domain.

|===

PMP can be used for more static and deterministic use cases.

MTT can be used where more fine grained dynamic resource management across
supervisor domain boundaries is required.

[width=100%]
[%header, cols="5,20"]
|===

| ID#
| Requirement

| SR_SUD_002
| A system supporting supervisor domains MUST support supervisor domain
extensions for interrupts (Smsdia) and SHOULD support supervisor domain
extensions for external debug (TBD).

|===

===== Supervisor domains: Interrupts, External debug and Performance counters

*See chapter 6 (Smsdia) of the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor
Domains Access Protection] specification.*

*See the https://github.com/riscv-non-isa/riscv-external-debug-security[RISC-V External Debug Security Extension]
specification.*

*Browse the https://lists.riscv.org/g/tech-privileged[tech-privileged mailing list] for relevant background on performance
counters.*

These extensions enable management of interrupts, external debug, and
performance counters across supervisor domain boundaries. M-mode firmware
should context switch hart HPM event/counters to manage isolation of
performance counters:

* External debug can be enabled for one supervisor domain without affecting
other supervisor domains
* M-mode firmware manage interrupt routing and preemption across supervisor
domain boundaries
* M-mode firmware can ensure that performance counters cannot be used by
software in one supervisor domain to measure operations in other supervisor
domains

==== IOPMP

*See the https://github.com/riscv-non-isa/iopmp-spec[RISC-V IOPMP] specification.*

IOPMP is a system level component providing physical memory access control for
device-initiated transactions, complementing PMP and sPMP rules.

[#cat_sr_sub_iop]
[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOP_001
| A system which supports PMP/Smepmp, or sPMP, MUST implement IOPMP for device
access control unless the system supports IOMTT.

Depending in system design, IOMTT can enforce the same access control policies as IOPMP.

| SR_IOP_002
| IOPMP configurations MUST only be directly accessible to machine mode.
|===

NOTE: IOPMP defines multiple "models" for different system configurations.
Unless specified differently in the use cases in this specification, system
designers are free to choose any IOPMP model.

==== IOMTT

*See the https://github.com/riscv/riscv-smmtt[RISC-V Supervisor Domains Access
Protection] specification.*

IOMTT is a system level component providing physical memory access control for
device-initiated transactions, complementing MTT rules.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_001
| A system which supports MTT MUST implement IOMTT for access-control for
device-initiated memory accesses.

| SR_IOM_002
| IOMTT configurations MUST only be directly accessible to machine mode.

| SR_IOM_003
| A system which implements IOMTT MAY also implement IOPMP to access-control
device-initiated access to M-mode memory.

|===

NOTE: IOMTT can also be sufficient for protecting Root devices in the sense that
M-mode can enforce that its own resources are never assigned to another domain.
Use of IOPMP or similar still adds further protections. For example, a system
could require that Root devices are not able to access memory assigned to TEE
domain.

==== IOMMU

*See the https://github.com/riscv-non-isa/riscv-iommu[RISC-V IOMMU] specification.*

IOMMU is a system level component performing memory address translation from IO
Virtual Addresses to Physical Addresses thereby allowing devices to access virtual memory
locations. It complements the MMU.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_IOM_004
| Systems supporting MMU SHOULD also support IOMMU

| SR_IOM_005
| Systems supporting IOMMU MUST also enforce physical memory access control for
M-mode memory against device-initiated transactions (IOMTT or IOPMP).

|===

=== Software enforced memory tagging

*See the https://github.com/riscv/riscv-j-extension[RISC-V Pointer Masking] specification.*

_Memory tagging (MT)_, is a technique which can improve the memory safety of an
application. A part of the effective address of a pointer can be masked off
and used as a tag indicating the intended ownership or state of a pointer. The tag
can be used to track accesses across different regions as well as protecting
against pointer misuse such as "use-after-free". Pointer masking implementations should use
the proposed RISC-V pointer masking extension (Smmpm, Smnpm, Ssnpm).

With software based memory tagging the access rules encoded in tags are
enforced by software, such as the compiler and the C library.

See also hardware enforced memory tagging below.

=== Control flow integrity

*See the https://github.com/riscv/riscv-cfi[RISC-V Control Flow Integrity] specification.*

Control-flow Integrity (CFI) capabilities help defend against Return-Oriented
Programming (ROP) and Call/Jump-Oriented Programming (COP/JOP) style of
control-flow subversion attacks. Here an attacker attempts to modify return
addresses or call/jump address to redirect a victim to code used by the
attacker.

These attack methodologies use code sequences in authorized modules, with at
least one instruction in the sequence being a control transfer instruction that
depends on attacker-controlled data either in the return stack or in memory
used to obtain the target address for a call or jump.

Attackers stitch these
sequences together by diverting the control flow instructions (e.g., JALR,
C.JR, C.JALR), from their original target address to a new target via
modification in the return stack or in the memory used to obtain the jump/call
target address.

RISC-V provides two defenses:

* Shadow stacks (Zicfiss) - protect return addresses on call stacks
* Labeled Landing pads (Zicfilp) - protect target addresses in jumps and
branches

=== Cryptography

*See the https://github.com/riscv/riscv-crypto[RISC-V Cryptography Extension] specification.*

RISC-V includes ISA extensions in the following cryptographic areas:

* Scalar cryptography
* Vector cryptography
* Entropy source (scalar)

RISC-V cryptographic extensions are aimed at supporting efficient acceleration
of cryptographic operations at the ISA level. This can both help reduce the TCB of
an isolated component and also avoid hardware bottlenecks (for example, system
level cryptographic subsystems).

The entropy source extension provides an ISA level interface to a hardware
entropy source. Entropy source requirements can depend on use case or ecosystem
specific requirements and RISC-V does not provide any entropy source technical
specification. However, the entropy source ISA specification does contain general
recommendations and references.

[width=100%]
[%header, cols="5,20"]
|===
| ID#
| Requirement

| SR_CPT_001
| RISC-V systems SHOULD support either scalar or vector cryptographic ISA
extensions

| SR_CPT_002
| The entropy source ISA extension MUST be supported if either scalar or vector
cryptographic ISA extensions are supported.

|===

It is not necessary to support both scalar and vector operations, as a scalar
operation can be viewed as a vector of size 1.

=== Roadmap

There are a number of technologies that are being considered for possible future inclusion into the RISC-V Security
Model roadmap. The technologies that are currently in focus are enumerated here. These are subject to change.

==== Capability based architecture

===== CHERI

*See the https://github.com/riscv/riscv-cheri[RISC-V Specification for CHERI Extensions] specification.*

CHERI - an ISA technique that uses capability-based memory protection for spatial and temporal memory safety, compartmentalization, and control-flow enforcement.  Source code has to be recompiled to capture memory safety properties inherent in the source language.

===== Capstone

*See the https://github.com/project-starch/capstone-spec[Capstone-RISCV ISA Reference].*

Capstone is another ISA technique aiming to enable a capability architecture in software and hardwre.

==== Hardware enforced memory tagging

Hardware enforced memory tagging extends software based memory tagging (see
above) by moving enforcement of tagged rules to hardware. At present this technology is at a very early
stage of discussion for RISC-V.

==== Hardware-assisted Fault Isolation

_Hardware-assisted fault isolation (HFI)_ aims to provide lightweight in-process isolation to mitigate against errors
in one process compromising other processes within the same workload.

==== Lightweight isolation

Lighweight isolation aims to enable the isolation of M-Mode runtimes and libraries. At present this technology is at a very early
stage of discussion for RISC-V.

==== System integration

The _WorldGuard security model_ provides an open, system level approach to securing access to system wide resources by
by software applications. The WorldGuard model introduces a concept of Worlds with unique World IDs. Software running at
different RISC-V privilege levels can be assigned unique World IDs. System resources can be associated with lists of
World IDs to control accesses to those resources in a fine grained manner.

==== Cryptography enhancements

The _RISC-V Post Quantum Cryptography_ initiative aims to specify ISA extensions that enhance performance and
implementation efficiency for contemporary public-key cryptography, with a focus on standard Post-Quantum Cryptography
algorithms like Kyber, Dilithium, and others. The ISA design and evaluation prioritize the requirements of real-world
networked devices, ensuring that the Post-Quantum Cryptography (PQC) extensions effectively complement existing scalar
and vector cryptography extensions.

At present this technology is at a very early stage of discussion for RISC-V.

The _RISC-V High Assurance Cryptography_ initiative aims to specify ISA extensions for cryptography with additional
security features such as side-channel resistance.

At present this technology is at a very early stage of discussion for RISC-V.
